### ISSUE TITLE
TERM environment variable not set.

### ISSUE THREAD

**Issue by vmoskova** [F7YYY/CSC122#1]
In Xcode give me an error TERM environment variable not set.
Any ideas or suggestions, how to fix it?

**Comment by F7YYY** [comment]
Can you provide the step taken to reach this issue, and a screenshot of this error during compiling. 
Additionally which program did you run, and what operating system (Mac, Linux, Windows) and Integrated Development Environment (IDE) did you run this program on?

Assuming your using Mac (OSX); Others reported issues with system("clear") throwing an "TERM environment variable not set" with Xcode on OSX. I believe your fix may pertain to using a compiler like GCC or Macos's native compiler Clang. Try deleting system("clear") and allowing the program to unethically run, then we will know Xcode does not recognize this command in OSX's native system table. Otherwise for Windows, system("clear") is a Linux command therefore replace it with system("cls").

**Comment by vmoskova** [comment]
Thanks, I am on Mac using the Xcode. Yes, when I am deleting "clear", everything works great.

system("cls") is not working as well giving an error : sh: cls: command not found.

Thank you for your quick response.

**Comment by F7YYY** [comment]
That's good to note,
I don't personally own or use an Apple product but "cls" is strictly a Window's command to clear the terminal screen. I'm not absolutely sure what system function (I.E. ~ system("")) Xcode uses to send "clear" to the Mac terminal. But my best call is to use the native libraries in Mac (Linux Distro) to compile and run code for supported "TERMS".

Since Xcode is technically bloatware on Operating Systems outside Windows. I have suspicion your working in a code editor instead of an IDE. For example VScode, you can change your C++ GUI settings to allow Clang or GCC preferably instead of Xcode's compiler.
